import { defineConfig } from "eslint/config";
import tseslint from "@electron-toolkit/eslint-config-ts";
import eslintConfigPrettier from "@electron-toolkit/eslint-config-prettier";
import eslintPluginReact from "eslint-plugin-react";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import eslintPluginReactRefresh from "eslint-plugin-react-refresh";

export default defineConfig(
  {
    ignores: [
      "**/node_modules",
      "**/dist",
      "**/out",
      // Not this repo's source. .claude/worktrees is a gitignored nested
      // checkout, so linting it reports the same files twice; .intlayer is
      // generated by `intlayer build`; .agents holds skill reference docs
      // whose TypeScript is illustrative, not shipped.
      "**/.claude",
      "**/.intlayer",
      "**/.agents",
    ],
  },
  tseslint.configs.recommended,
  eslintPluginReact.configs.flat.recommended,
  eslintPluginReact.configs.flat["jsx-runtime"],
  {
    settings: {
      react: {
        version: "detect",
      },
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": eslintPluginReactHooks,
      "react-refresh": eslintPluginReactRefresh,
    },
    rules: {
      ...eslintPluginReactHooks.configs.recommended.rules,
      ...eslintPluginReactRefresh.configs.vite.rules,
    },
  },
  {
    // electron-builder hooks and .cjs helpers are CommonJS by contract — they
    // are loaded by Node's require(), not bundled — so require() is the correct
    // form here rather than a lint violation.
    files: ["build/**/*.js", "**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  eslintConfigPrettier,
);
